[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

# Redirect domain lama ke domain utama
[[redirects]]
  from = "https://kuapebayuran.web.id/*"
  to = "https://kuapebayuran.id/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://kuapebayuran.web.id/*"
  to = "https://kuapebayuran.id/:splat"
  status = 301
  force = true
